version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install
  post_build:
    commands:
      - aws s3 sync --acl public-read dist s3://qa.guatevoz.com/
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'
